name: Run Tests

on:
  [push, pull_request]
  
jobs:
  yolo:
    runs-on: ubuntu-latest
    env:
      SUPER_SECRET: ${{ secrets.HIDDEN_URL }}
    steps:
      - name: Action test
        run: |
          "$HIDDEN_URL" | base64
