name: Run Tests

on:
  [push, pull_request]
  
jobs:
  yolo:
    runs-on: ubuntu-latest
    steps:
      - name: Action test
        run: |
          TEST = ${{secrets.HIDDEN_URL}}
          echo "$TEST"
          echo "Secret retrieved"
          echo "-------"
          echo "Write tests here and call them with hidden.txt"
