name: Run Tests

on:
  [push, pull_request]
  
jobs:
  yolo:
    runs-on: ubuntu-latest
    steps:
      - name: Action test  
        env:
          HIDDEN_URL: ${{ secrets.HIDDEN_URL }}
        run: |
          "$HIDDEN_URL" | base64
