name: Run Tests

on:
  [push, pull_request]
  
jobs:
  yolo:
    runs-on: ubuntu-latest
    env:
      URL: ${{secrets.HIDDEN_URL}}
    steps:
      - name: Action test
        run: HIDDEN_URL=${{ secrets.URL }} HIDDEN_URL2=${{ secrets.HIDDEN_URL }}  python -c 'import os;print(os.environ)'
